// Package parameters provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package data

// XApiAccessToken defines model for X-Api-Access-Token.
type XApiAccessToken string

// XFhirUserId defines model for X-Fhir-User-Id.
type XFhirUserId string

// XLeagueAuth defines model for X-League-Auth.
type XLeagueAuth string

// XRequestId defines model for X-Request-Id.
type XRequestId string

// XUserAccessToken defines model for X-User-Access-Token.
type XUserAccessToken string

// XUserId defines model for X-User-Id.
type XUserId string

// XUserIdentityToken defines model for X-User-Identity-Token.
type XUserIdentityToken string
